version: "3.1"
services:
    db:
        image: mysql:latest
        restart: always
        container_name: dbfinal
        environment: 
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        ports:
            - '3308:3306'
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default
    www:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - default     
volumes:
    persistent: